#!/bin/bash
# ==============================================================================
# Home Assistant Community Add-on: NSPanel Manager
# Runs the NSPanel Manager dashboard app
# ==============================================================================
if [ "$TZ" != "" ]; then
	echo "Setting /etc/timezone to $TZ"
	echo "$TZ" >/etc/timezone
fi

cd nspanelmanager || exit

echo "Running migrations..."
/usr/local/bin/python ./manage.py migrate

echo "Starting server"
/usr/local/bin/python ./manage.py runserver 0.0.0.0:8000

echo "Stopping all python applications"
for app in $(pgrep python); do
	kill "$app"
done
